server:
  port: 8081
# DataSource Config
#    url: jdbc:postgresql://192.168.234.128:15400/adsad2?serverTimezone=GMT%2B8
#    username: hallo
#    password: 20031124sfw.
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adsad2?serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
#    password: 123456
  # 时间格式转换
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    # 引入application-email配置文件
    include: email

jasypt:
  encryptor:
    password: Angel
    algorithm: PBEWithMD5AndDES
#    spring:
#      security:
#        user:
#          name: user
#          password: 111111

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

itbluebox:
  jwt:
    header: Authorization
    expire: 604800 #七天
    secret: 212wdseqw23red232r3rds23r21212hg



